spring:
  datasource:
    jdbcurl: jdbc:tc:postgis:16-3.4:///notivent?TC_INITSCRIPT=sql/dbInitTest.sql
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: postgres
    password: 05konrad05

  liquibase:
    enabled: false

mybatis:
  configuration:
    call-setters-on-nulls: false